# -*- coding: utf-8 -*-
"""Introduction to Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LgQAzE2pmj8HF4anSSDcsWjCS9rgqxJ

1. Print Function
"""

print (12,end ='-')
print(12.5)
print('Amankant Pathak')
print(True)
print()
print('-------------')
print (12,25,True,'Amankant Pathak')

"""2. Type"""

print (type (12))
print (type (12.5))
print (type ('Amankant Pathak'))
print (type (True))

"""3. Operators

3.1 Arithmetic

3.1.1 Int-int
"""

print (12+12)
print (12-5)
print(12*5)
print(12/5)
print(12//5)
print(12%5)
print(12**5)

"""3.1.2 Int - Float"""

print (12+5.2)
print (12-5.2)
print(12*5.2)
print(12/5.2)
print(12//5.2)
print(12%5.2)
print(12**5.2)

"""3.1.3 Int-string"""

print(12*'Amankant Pathak')

"""3.1.4) Int - Boolean"""

print(12+True)
print(12-False)
print(12*True)
print(12/True)
print(12//True)
print(12%True)
print(12**True)

"""3.2) Comparison"""

print(10>5)
print(10<5)
# print(a=5)
print(10==5)
print(10!=5)
print(5>=5)
print(5>5)
print(10<=5)

"""3.3) Logical"""

n = 70

print((n%7 == 0) and (n%5 == 0))
print((n%7 == 0) or (n%5 == 0))

print((n%7 == 0) and (n%5 == 0) and not (n%9 == 0))
print((n%7 == 0) and (n%5 == 0) and not (n%9 == 0) and (n%2 == 0))

4. Typecasting

"""4.1) Int"""

print(int(12.99999))
print(int('4623'))
print(int(True))
print(int(False))

"""4.2) Float"""

print(float(12))
print(float('462332'))
print(float(True))
print(float(False))

"""4.3) Boolean"""

print(bool(0))
print(bool(0.0))
print(bool(' '))